trigger:
  branches:
    include:
      - main

pool:
  name: 'Linux'

variables:
  TF_VAR_client_id: $(azCli.client_id)
  TF_VAR_client_secret: $(azCli.client_secret)
  TF_VAR_sub_id: $(azCli.subscription_id)
  TF_VAR_tenant_id: $(azCli.tenant_id)

steps:
 - script: 
      az login --service-principal -u $(TF_VAR_client_id) -p $(TF_VAR_client_secret) --tenant $(TF_VAR_tenant_id)
      az account set --subscription $(TF_VAR_sub_id)
   displayName: 'Authenticate with Azure CLI'
