trigger:
  - none

pool:
  name: 'Linux'  # Adjust as needed

variables:
  TF_VAR_client_id: $(azCli.client_id)
  TF_VAR_client_secret: $(azCli.client_secret)
  TF_VAR_sub_id: $(azCli.subscription_id)
  TF_VAR_tenant_id: $(azCli.tenant_id)

steps:
  # AzureCLI task with service connection
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azurerm'  # Replace with your service connection name
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Setting up Azure subscription context..."
        echo "Client ID: $TF_VAR_client_id"
        echo "Tenant ID: $TF_VAR_tenant_id"
        echo "Subscription ID: $TF_VAR_sub_id" 
        
        az account set --subscription $TF_VAR_sub_id
        echo "Subscription set successfully."

    displayName: 'Azure CLI Task - Authenticate and Set Subscription'

  - script: |
      ls -l
      cd terrafom
      terraform init
    displayName: 'Terraform Init'
  
  - script: |
     ls -l
     terrafrom plan
    displayName: 'terrafrom plan'
